export const systemConstants = {
    SET_MAIN_SCREEN: 'SET_MAIN_SCREEN',
    SET_SCALE: 'SET_SCALE'
}

export const companyConstants = {
    SET_PAGES: 'SET_PAGES',
    SET_SELECTED_PAGE_INDEX: 'SET_SELECTED_PAGE_INDEX'    
}

export const customersConstants = {
    SET_CUSTOMERS: 'SET_CUSTOMERS',
    SET_SELECTED_CUSTOMER: 'SET_SELECTED_CUSTOMER',
    SET_CUSTOMER_PANELS: 'SET_CUSTOMER_PANELS',
    SET_SELECTED_CONTACT: 'SET_SELECTED_CONTACT',
    SET_SELECTED_NOTE: 'SET_SELECTED_NOTE',
    SET_SELECTED_DIRECTION: 'SET_SELECTED_DIRECTION',
    SET_CONTACT_SEARCH: 'SET_CONTACT_SEARCH',
    SET_CUSTOMER_SEARCH: 'SET_CUSTOMER_SEARCH',
    SET_AUTOMATIC_EMAILS_TO: 'SET_AUTOMATIC_EMAILS_TO',
    SET_AUTOMATIC_EMAILS_CC: 'SET_AUTOMATIC_EMAILS_CC',
    SET_AUTOMATIC_EMAILS_BCC: 'SET_AUTOMATIC_EMAILS_BCC',
    SET_SHOWING_CONTACT_LIST: 'SET_SHOWING_CONTACT_LIST',
    SET_CUSTOMER_CONTACTS: 'SET_CUSTOMER_CONTACTS',
    SET_CONTACT_SEARCH_CUSTOMER: 'SET_CONTACT_SEARCH_CUSTOMER',
    SET_IS_EDITING_CONTACT: 'SET_IS_EDITING_CONTACT',
    SET_SELECTED_DOCUMENT: 'SET_SELECTED_DOCUMENT',
    SET_DOCUMENT_TAGS: 'SET_DOCUMENT_TAGS',
    SET_SELECTED_DOCUMENT_NOTE: 'SET_SELECTED_DOCUMENT_NOTE'
}

export const carriersConstants = {
    SET_CARRIERS: 'SET_CARRIERS',
    SET_SELECTED_CARRIER: 'SET_SELECTED_CARRIER',
    SET_CARRIER_PANELS: 'SET_CARRIER_PANELS',
    SET_SELECTED_CONTACT: 'SET_SELECTED_CONTACT',
    SET_SELECTED_NOTE: 'SET_SELECTED_NOTE',
    SET_SELECTED_DIRECTION: 'SET_SELECTED_DIRECTION',
    SET_CONTACT_SEARCH: 'SET_CONTACT_SEARCH',
    SET_CARRIER_SEARCH: 'SET_CARRIER_SEARCH',
    SET_SHOWING_CONTACT_LIST: 'SET_SHOWING_CONTACT_LIST',
    SET_CARRIER_CONTACTS: 'SET_CARRIER_CONTACTS',
    SET_CONTACT_SEARCH_CARRIER: 'SET_CONTACT_SEARCH_CARRIER',
    SET_IS_EDITING_CONTACT: 'SET_IS_EDITING_CONTACT',
    SET_SELECTED_DOCUMENT: 'SET_SELECTED_DOCUMENT',
    SET_DOCUMENT_TAGS: 'SET_DOCUMENT_TAGS',
    SET_SELECTED_DOCUMENT_NOTE: 'SET_SELECTED_DOCUMENT_NOTE',
    SET_DRIVERS: 'SET_DRIVERS',
    SET_SELECTED_DRIVER: 'SET_SELECTED_DRIVER',
    SET_EQUIPMENTS: 'SET_EQUIPMENTS',
    SET_INSURANCE_TYPES: 'SET_INSURANCE_TYPES',
    SET_SELECTED_EQUIPMENT: 'SET_SELECTED_EQUIPMENT',
    SET_SELECTED_INSURANCE_TYPE: 'SET_SELECTED_INSURANCE_TYPE',
    SET_MAILING_ADDRESS: 'SET_MAILING_ADDRESS',
    SET_FACTORING_COMPANY_SEARCH: 'SET_FACTORING_COMPANY_SEARCH',
    SET_FACTORING_COMPANIES: 'SET_FACTORING_COMPANIES',
}