export const systemConstants = {
    SET_MAIN_SCREEN: 'SET_MAIN_SCREEN'
}

export const companyConstants = {
    SET_PAGES: 'SET_PAGES',
    SET_SELECTED_PAGE_INDEX: 'SET_SELECTED_PAGE_INDEX',
    SET_SCALE: 'SET_SCALE'
    
}

export const customersConstants = {
    SET_CUSTOMERS: 'SET_CUSTOMERS',
    SET_SELECTED_CUSTOMER: 'SET_SELECTED_CUSTOMER',
    SET_CUSTOMER_PANELS: 'SET_CUSTOMER_PANELS',
    SET_SELECTED_CONTACT: 'SET_SELECTED_CONTACT',
    SET_SELECTED_NOTE: 'SET_SELECTED_NOTE',
    SET_SELECTED_DIRECTION: 'SET_SELECTED_DIRECTION',
    SET_CONTACT_SEARCH: 'SET_CONTACT_SEARCH',
    SET_CUSTOMER_SEARCH: 'SET_CUSTOMER_SEARCH',
    SET_AUTOMATIC_EMAILS_TO: 'SET_AUTOMATIC_EMAILS_TO',
    SET_AUTOMATIC_EMAILS_CC: 'SET_AUTOMATIC_EMAILS_CC',
    SET_AUTOMATIC_EMAILS_BCC: 'SET_AUTOMATIC_EMAILS_BCC',
    SET_SHOWING_CONTACT_LIST: 'SET_SHOWING_CONTACT_LIST',
    SET_CUSTOMER_CONTACTS: 'SET_CUSTOMER_CONTACTS',
    SET_CONTACT_SEARCH_CUSTOMER: 'SET_CONTACT_SEARCH_CUSTOMER'
}